export { default as PairedDevicesPanel } from './PairedDevicesPanel'
export { default as DeviceStatus } from './DeviceStatus'
export { default as Permissions } from './Permissions'
export { default as Rules } from './Rules'
export { default as Welcome } from './welcome'
