import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import { bumpVersion, parseSemver } from '../bump-version-lib.js'
import { updateCargoLock } from '../bump-version.js'

describe('bumpVersion prerelease patch', () => {
  it('keeps base version when creating first alpha prerelease', () => {
    expect(bumpVersion('0.1.0', 'patch', 'alpha')).toBe('0.1.0-alpha.1')
  })

  it('increments alpha prerelease number on repeat', () => {
    expect(bumpVersion('0.1.0-alpha.1', 'patch', 'alpha')).toBe('0.1.0-alpha.2')
  })
})

describe('parseSemver target version', () => {
  it('accepts explicit prerelease target version', () => {
    const parsed = parseSemver('0.1.0-alpha.2')
    expect(parsed.prerelease).toBe('alpha')
    expect(parsed.prereleaseVersion).toBe(2)
  })
})

describe('updateCargoLock', () => {
  const tempDirs: string[] = []
  const originalCwd = process.cwd()

  afterEach(() => {
    process.chdir(originalCwd)
    while (tempDirs.length > 0) {
      const dir = tempDirs.pop()
      if (dir) {
        fs.rmSync(dir, { recursive: true, force: true })
      }
    }
  })

  it('updates the root package version in Cargo.lock', () => {
    const repoDir = fs.mkdtempSync(path.join(os.tmpdir(), 'bump-version-'))
    tempDirs.push(repoDir)
    process.chdir(repoDir)

    fs.mkdirSync(path.join(repoDir, 'src-tauri'), { recursive: true })
    fs.writeFileSync(
      path.join(repoDir, 'src-tauri', 'Cargo.toml'),
      '[package]\nname = "uniclipboard"\nversion = "0.2.0-alpha.4"\n',
      'utf8'
    )
    fs.writeFileSync(
      path.join(repoDir, 'src-tauri', 'Cargo.lock'),
      '# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "uniclipboard"\nversion = "0.2.0-alpha.4"\ndependencies = []\n',
      'utf8'
    )

    const result = updateCargoLock('0.2.0-alpha.5', false)
    const updated = fs.readFileSync(path.join(repoDir, 'src-tauri', 'Cargo.lock'), 'utf8')

    expect(result.old).toBe('0.2.0-alpha.4')
    expect(result.new).toBe('0.2.0-alpha.5')
    expect(updated).toContain('name = "uniclipboard"\nversion = "0.2.0-alpha.5"')
  })

  it('does not write Cargo.lock during dry run', () => {
    const repoDir = fs.mkdtempSync(path.join(os.tmpdir(), 'bump-version-'))
    tempDirs.push(repoDir)
    process.chdir(repoDir)

    fs.mkdirSync(path.join(repoDir, 'src-tauri'), { recursive: true })
    fs.writeFileSync(
      path.join(repoDir, 'src-tauri', 'Cargo.toml'),
      '[package]\nname = "uniclipboard"\nversion = "0.2.0-alpha.4"\n',
      'utf8'
    )
    const lockPath = path.join(repoDir, 'src-tauri', 'Cargo.lock')
    const original =
      '# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "uniclipboard"\nversion = "0.2.0-alpha.4"\ndependencies = []\n'
    fs.writeFileSync(lockPath, original, 'utf8')

    const result = updateCargoLock('0.2.0-alpha.5', true)
    const after = fs.readFileSync(lockPath, 'utf8')

    expect(result.old).toBe('0.2.0-alpha.4')
    expect(result.new).toBe('0.2.0-alpha.5')
    expect(after).toBe(original)
  })
})
